In [1]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json
import requests
import urllib.request
from pandas.io.json import json_normalize

In [3]:
# Import coins file as DataFrame
coins_df = pd.read_csv("../resources/coingecko_symbols.csv")

In [4]:
# Add columns for sentiment
# Note that we used "" to specify initial entry.
coins_df["avg_sentiment"] = ""
coins_df["avg_sentiment_1y"] = ""
coins_df["avg_sentiment_pct_chg"] = ""
coins_df["social_score_1y"] = ""
coins_df["social_score_1y_pct_chg"] = ""
coins_df

,symbol,id,avg_sentiment,avg_sentiment_1y,avg_sentiment_pct_chg,social_score_1y,social_score_1y_pct_chg
0,btc,bitcoin,,,,,
1,eth,ethereum,,,,,
2,usdt,tether,,,,,
3,bnb,binancecoin,,,,,
4,ada,cardano,,,,,
...,...,...,...,...,...,...,...
245,wnxm,wrapped-nxm,,,,,
246,tlm,alien-worlds,,,,,
247,loc,lockchain,,,,,
248,inst,instadapp,,,,,
249,keep,keep-network,,,,,

In [5]:
base_url = "https://api.lunarcrush.com/v2?data=assets&key=b9c27jge0ku5kvggiqykth&change=1y&data_points=0"

In [6]:
# Use the coins_df file to select symbol from sentiment data
for index, row in coins_df.iterrows():
    # get coin symbol
    symbol = row["symbol"]

    # Use the search term: "Coin" and our symbol
    url = f"{base_url}&symbol={symbol}"

    # make request and print url
    response = requests.get(url).json()
    

#     # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        coins_df.loc[index,"avg_sentiment"] = response["data"][0]["average_sentiment"]
        coins_df.loc[index,"avg_sentiment_1y"] = response["data"][0]["average_sentiment_1y"]
        coins_df.loc[index,"avg_sentiment_pct_chg"] = response["data"][0]["average_sentiment_1y_percent_change"]
        coins_df.loc[index,"social_score_1y"] = response["data"][0]["social_score_1y"]
        coins_df.loc[index,"social_score_1y_pct_chg"] = response["data"][0]["social_score_1y_percent_change"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [7]:
coins_df

,symbol,id,avg_sentiment,avg_sentiment_1y,avg_sentiment_pct_chg,social_score_1y,social_score_1y_pct_chg
0,btc,bitcoin,3.6,3.61726,-1.328976,406086613362,303.522034
1,eth,ethereum,3.6,3.69014,0.021413,39344245361,158.90738
2,usdt,tether,3.7,3.62356,-3.736252,2074291768,110.53714
3,bnb,binancecoin,3.6,3.69205,-2.145508,2432539631,180.836315
4,ada,cardano,3.7,3.63233,-3.282813,6456894072,304.318436
...,...,...,...,...,...,...,...
245,wnxm,wrapped-nxm,,,,,
246,tlm,alien-worlds,,,,,
247,loc,lockchain,3,3.10027,1.845878,8292035,240.540773
248,inst,instadapp,,,,,
249,keep,keep-network,3,3.27552,None,44376100,None

In [8]:
coins_df.describe()

,symbol,id,avg_sentiment,avg_sentiment_1y,avg_sentiment_pct_chg,social_score_1y,social_score_1y_pct_chg
count,250,250,250,250,175,250,173
unique,248,250,22,207,143,217,141
top,steth,swissborg,3,,,,
freq,2,1,68,33,33,33,33

In [9]:
coins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   symbol                   250 non-null    object
 1   id                       250 non-null    object
 2   avg_sentiment            250 non-null    object
 3   avg_sentiment_1y         250 non-null    object
 4   avg_sentiment_pct_chg    175 non-null    object
 5   social_score_1y          250 non-null    object
 6   social_score_1y_pct_chg  173 non-null    object
dtypes: object(7)
memory usage: 13.8+ KB

In [11]:
# Create csv file with lunarcrush sentiment data
coins_df.to_csv("../resources/crypto_sentiment.csv", index=False)